### ISSUE TITLE
Subtitle files not showing up again.

### ISSUE THREAD

**Issue by MidoriGreenMidori** [rsimmons/subadub#17]
![image](https://user-images.githubusercontent.com/58581941/72314609-76618500-3644-11ea-98be-42fbbd0d63ca.png)

**Comment by Essam311** [comment]
Install this chrome extension and subadub will work again.

https://chrome.google.com/webstore/detail/language-learning-with-ne/hoombieeljmmljlkjmnheibnpciblicm

**Comment by knl3drs** [comment]
me too.

const WEBVTT_FMT = 'webvtt-lssdh-ios8'; //***old?***

const WEBVTT_FMT = 'nflx-cmisc'; //***new?***


fetch(url).then(function(response) {
        if (response.ok) {
          return response.blob();
        }
        throw new Error('Bad response to WebVTT request');
      }).then(function(blob) {
        //***maybe this code isn't running?***
        webvttCache.set(cacheKey, new Blob([blob], {type: 'text/vtt'})); // set type to avoid warning
        renderAndReconcile();
      }).catch(function(error) {
        console.error('Failed to fetch WebVTT file', error.message);
      });

**Comment by Essam311** [comment]
> 
> 
> me too.
> 
> const WEBVTT_FMT = 'webvtt-lssdh-ios8'; //_**old?**_
> 
> const WEBVTT_FMT = 'nflx-cmisc'; //_**new?**_
> 
> fetch(url).then(function(response) {
> if (response.ok) {
> return response.blob();
> }
> throw new Error('Bad response to WebVTT request');
> }).then(function(blob) {
> //_**maybe this code isn't running?**_
> webvttCache.set(cacheKey, new Blob([blob], {type: 'text/vtt'})); // set type to avoid warning
> renderAndReconcile();
> }).catch(function(error) {
> console.error('Failed to fetch WebVTT file', error.message);
> });

You can use this workaround, install this chrome extension and subadub will work again. 

https://chrome.google.com/webstore/detail/language-learning-with-ne/hoombieeljmmljlkjmnheibnpciblicm

In the "Learn Language With Netflix" extension interface turn it off if you will only use it to make Subadub working again.

![55](https://user-images.githubusercontent.com/59211054/72340972-d4887980-36d1-11ea-8dea-fa59ca04686c.png)

**Comment by knl3drs** [comment]
Thank you so much!

**Comment by Essam311** [comment]
Installing this extension on Google chrome makes Subadub works too.

https://github.com/Nitrino/easysubs

Subadub might get fixed based on this code.

https://github.com/Nitrino/easysubs/blob/master/src/services/netflix.ts

**Comment by Essam311** [comment]
Subadub fixed for me using @mwhirls fix.

https://github.com/Essam311/subadub/commit/08d2e8db6138932b7165d59d836482c18e2cc79e

**Comment by Essam311** [comment]
Using @mwhirls fix https://github.com/mwhirls/jimakun/commit/9c430445517061384326dac4f96589625d5f99da for the same problem in his script "jimakun" fixed Subadub for me.

https://github.com/Essam311/subadub/commit/b3626affe615b14b52b463b2bcdfb7943a97e3a8

@mwhirls Could you please port your fix to Subadub?

**Comment by mwhirls** [comment]
@Essam311 I don't mind, I can do it later today.  Since you already have the fix in your fork though, feel free to go ahead and put up a pull request for it if you'd like.

**Comment by Essam311** [comment]
@mwhirls Thanks you so much, I made a pull request.

**Comment by Essam311** [comment]
@mwhirls Sorry I will close my PR, the fix will be much better if you ported it.

**Comment by mwhirls** [comment]
@Essam311  Oh okay, no problem.  Pull request added that fixes the bug: https://github.com/rsimmons/subadub/pull/19

**Comment by Essam311** [comment]
@mwhirls Thank you so much, the fix is working great on both Firefox and Google chrome.

**Comment by bun906** [comment]
same problem.

**Comment by Essam311** [comment]
@bun906 Until @rsimmons merges the new fix and upload a new version to Chrome Web Store you can install this new working version of Subadub with the same steps here on Google chrome.

[dist.zip](https://github.com/rsimmons/subadub/files/4076246/dist.zip)

https://github.com/mwhirls/jimakun#installation

**Comment by bun906** [comment]
@Essam311 Thanks, it's working fine.

**Comment by rsimmons** [comment]
The new version has been published for both Chrome and Firefox. Thank you @MidoriGreenMidori for reporting, and thank you @mwhirls for the patch!

**Comment by Essam311** [comment]
@mwhirls Subadub is broken again, most likely a similar problem for the previous one, would you please check if it could be fixed? Thanks.

**Comment by mwhirls** [comment]
@Essam311 Yeah, it was the same issue, Netflix keeps changing their API.  I put up a more robust fix this time, so hopefully it will be less of an issue in the future.

**Comment by Essam311** [comment]
@mwhirls Thank you so much, I tested your PR and it works perfectly on Google Chrome.

**Comment by bun906** [comment]
Yep, Subadub is broken again :(

**Comment by Essam311** [comment]
@bun906 You could use the fixed Subadub from here.

https://github.com/rsimmons/subadub/issues/20#issuecomment-612777747

**Comment by bun906** [comment]
> @bun906 You could use the fixed Subadub from here.
> 
> [#20 (comment)](https://github.com/rsimmons/subadub/issues/20#issuecomment-612777747)

Thanks, it worked :)
