### ISSUE TITLE
All available subtitles are not showing in dropdown

### ISSUE THREAD

**Issue by MaxCilauro** [rsimmons/subadub#20]
Available Netflix subtitles differ from the Subadub's dropdown list:

(Netflix: Japanese [CC], Danish, English, German, Swedish)
<img width="523" alt="Japanese [CC], Danish, English, German, Swedish subtitles" src="https://user-images.githubusercontent.com/13527685/74101196-854e3100-4b37-11ea-85fc-2fdf83f8fa35.png">

(Subadub: Danish, English, Swedish)
<img width="467" alt="Danish, English, Swedish" src="https://user-images.githubusercontent.com/13527685/74101198-88e1b800-4b37-11ea-9211-67bfe292fe0d.png">

Used latest master, on Chrome.

**Comment by Essam311** [comment]
Thank you so much, your PR fixed this problem for me.

**Comment by Essam311** [comment]
Thank you so much, your PR fixed this problem for me.

Locke & Key using Subadub 0.1.5

![11](https://user-images.githubusercontent.com/59211054/74218652-3f1ddc80-4cb3-11ea-9845-048079607c7c.png)


Locke & Key using Subadub 0.1.6

![22](https://user-images.githubusercontent.com/59211054/74218662-447b2700-4cb3-11ea-8bf6-d79669bdf0db.png)

**Comment by Essam311** [comment]
@MaxCilauro Thank you so much for your PR, it works fine for me.

For anyone wants to install the fixed Subadub on Firefox, you could install it manually using this file 

https://github.com/Essam311/subadub/raw/Essam311-patch-1/subadub-0.1.6-fx.xpi

Here are the instructions for installing Subadub manually on Firefox, remove Subadub 0.1.5 first.

https://www.wikihow.com/Install-Firefox-Extensions#Installing-Extensions-Manually-from-an-XPI-File

The fixed Subadub could be installed manually on Google Chrome using "dist" folder

https://codeload.github.com/MaxCilauro/subadub/zip/fix-show-all-subs

Use the same steps here for installing the fixed Subadub manually on Google Chrome, remove Subadub 0.1.5 first, and don't move "dist" folder from its place after installing the fixed Subadub manually on Google Chrome.

https://github.com/mwhirls/jimakun#installation
