### ISSUE TITLE
Not working on some videos.

### ISSUE THREAD

**Issue by nanpuhaha** [rsimmons/subadub#26]
Not working on some videos such as 
- https://www.netflix.com/watch/80215997

**Comment by rsimmons** [comment]
Thanks for reporting this. I see the issue too, I will look into fixing it.

In the meantime, I noticed this: On the "home" screen in Netflix, if I click on the thumbnail video for a show, the problem occurs. But if I select a specific episode or hit the play button (right arrow), it doesn't occur. Perhaps you can use this as a workaround in the meantime.

**Comment by rsimmons** [comment]
Fixed in commit https://github.com/rsimmons/subadub/commit/1826ed35c1884383d21a879c03957e96562bb682, pending release.

**Comment by rsimmons** [comment]
The new version (0.1.7) is up for Chrome and Firefox now, so whenever your browser updates to it, it should work.
