### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by fis60** [rsimmons/subadub#28]
First Thank you very much for this amazing tool i have been using it for a long time with no issues, i think Netflix updated something which led the tool to stop working anymore, i hope someone will be able to fix it.

Thanks

**Comment by rsimmons** [comment]
Thanks for reporting this. I just tried it, and it worked for me on one show at least. Could you maybe link me to a specific show that doesn't work for you, and confirm what country you're accessing from? It might also be possible that Netflix is mid-way through an update, and it will soon break for me as well.

**Comment by fis60** [comment]
Thanks for answering i tried so many nothing works for me 2 devices mac and pc, i am connecting through UAE i also tested vpn USA and UK with no luck. 

https://www.netflix.com/watch/80988988

**Comment by fis60** [comment]
i tested this version which i don’t remember from where i got, it works but buggy https://www19.zippyshare.com/v/Y0URzgYq/file.html

**Comment by fis60** [comment]
i found a temporary solution netflix is testing an updated player U/I i opt out and now it works
https://www.netflix.com/DoNotTest

**Comment by rsimmons** [comment]
Thanks for figuring this out! I guess if they roll out the updated player, I will make the fix then, since I don't know of a way for me to opt-in to that new player if I haven't gotten it.
