### ISSUE TITLE
Filenames are "broken" when downloading

### ISSUE THREAD

**Issue by rsimmons** [rsimmons/subadub#32]
Just so you know, the filenames are still "broken" when downloading
Since episode name, season number and episode number get removed from the dom when no mouse movement is happening they are not included in the filename.

Therefore filenames are always <netflix_id>_<language_tag>.srt

_Originally posted by @juligreen in https://github.com/rsimmons/subadub/issues/29#issuecomment-915985944_

**Comment by juligreen** [comment]
Netflix now exposes these attributes over it's api
```js
netflix.appContext.state.playerApp.getAPI().getVideoMetadataByVideoId(<currentEpisodeID>).getCurrentVideo().getEpisodeNumber()
```
